spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/eshop
    username: hefeng
    password: hefeng
  security:
    user:
      name: hefeng
      password: 123456
      roles: Admin


  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    root: info
    com.hef.ecommerce: debug

